package com.alterego.flickrtest;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table FLICKR_SEARCH_DAO_ENTRY.
 */
public class FlickrSearchDaoEntry {

    private Long id;
    private String flickr_response_string;
    private String flickr_search_string;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public FlickrSearchDaoEntry() {
    }

    public FlickrSearchDaoEntry(Long id) {
        this.id = id;
    }

    public FlickrSearchDaoEntry(Long id, String flickr_response_string, String flickr_search_string) {
        this.id = id;
        this.flickr_response_string = flickr_response_string;
        this.flickr_search_string = flickr_search_string;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFlickr_response_string() {
        return flickr_response_string;
    }

    public void setFlickr_response_string(String flickr_response_string) {
        this.flickr_response_string = flickr_response_string;
    }

    public String getFlickr_search_string() {
        return flickr_search_string;
    }

    public void setFlickr_search_string(String flickr_search_string) {
        this.flickr_search_string = flickr_search_string;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
